### ISSUE TITLE
Unfair gang moves

### ISSUE THREAD

**Issue by Azemblage** [FutureShockco/drugwars.io#70]
### Expected behavior
Each player if they are in a gang or not have to send an attack to collect information first and then attack after gathering that information.
### Actual behavior
There are gangs that are using one person to collect information that has low resources and after report to the boss or gang leader with much more resources and units to attack... that for me is unfair advantage and tricking the game. 
Also the battles incoming are lagging and you can be seeing a page and on the next moment you reload every single resource is gone.. wtf where is the clock for each battle ?

**Comment by hightouch67** [comment]
hey thanks for your feedback @Azemblage but spying enemies and reporting the information to your gang members is definitely a part of the game. You can even infiltrate enemy gangs with an account to know what they do and if you can gather some secret information to share with your allies.

For the incoming battles it should be improved since you reported this issue and we will continue to improve it so you don't face anymore the problem to getting attacked without knowing it.
